import { bookingConfig } from "@/config/booking";
import { bookingVehicles } from "@/data/booking-vehicles";
import { createTripSchema } from "@/schemas/booking";
import type { BookingDraft, TripDetails, TripType } from "@/types/booking";
export const emptyDraft: BookingDraft = { trip: null, fare: null, vehicleId: null, passenger: null };
export function isVehicleEligible(vehicleId: string, passengers: number) { const vehicle = bookingVehicles.find((item) => item.id === vehicleId); return Boolean(vehicle && vehicle.availability !== "unavailable" && vehicle.passengers >= passengers); }
export function updateDraftTrip(draft: BookingDraft, trip: TripDetails) { return { ...draft, trip, fare: null, vehicleId: draft.vehicleId && isVehicleEligible(draft.vehicleId, trip.passengers) ? draft.vehicleId : null }; }
export function serializeDraft(draft: BookingDraft) { return JSON.stringify({ trip: draft.trip, vehicleId: draft.vehicleId }); }
export function parseStoredDraft(value: string | null): BookingDraft { if (!value) return emptyDraft; try { const parsed: unknown = JSON.parse(value); if (!parsed || typeof parsed !== "object") return emptyDraft; const item = parsed as Record<string, unknown>; const tripResult = createTripSchema().safeParse(item.trip); const vehicleId = typeof item.vehicleId === "string" && bookingVehicles.some((vehicle) => vehicle.id === item.vehicleId) ? item.vehicleId : null; return { ...emptyDraft, trip: tripResult.success ? tripResult.data : null, vehicleId }; } catch { return emptyDraft; } }
const tripTypes: TripType[] = ["one-way", "round-trip", "outstation"];
export function parseTripSearchParams(params: URLSearchParams, now = new Date()): TripDetails | null { const passengers = Number(params.get("passengers") ?? "1"); const candidate = { tripType: tripTypes.includes(params.get("tripType") as TripType) ? params.get("tripType") : "one-way", pickup: params.get("pickup") ?? "", drop: params.get("drop") ?? "", date: params.get("date") ?? "", time: params.get("time") ?? "", returnDate: params.get("returnDate") || undefined, returnTime: params.get("returnTime") || undefined, passengers }; const result = createTripSchema(now).safeParse(candidate); return result.success ? result.data : null; }
export function parseTripPrefill(params: URLSearchParams): Partial<TripDetails> { const prefill: Partial<TripDetails> = {}; const tripType = params.get("tripType"); if (tripTypes.includes(tripType as TripType)) prefill.tripType = tripType as TripType; const pickup = params.get("pickup")?.trim(); const drop = params.get("drop")?.trim(); if (pickup && pickup.length <= 120) prefill.pickup = pickup; if (drop && drop.length <= 120) prefill.drop = drop; const date = params.get("date"); const time = params.get("time"); const returnDate = params.get("returnDate"); const returnTime = params.get("returnTime"); if (date && /^\d{4}-\d{2}-\d{2}$/.test(date)) prefill.date = date; if (time && /^([01]\d|2[0-3]):[0-5]\d$/.test(time)) prefill.time = time; if (returnDate && /^\d{4}-\d{2}-\d{2}$/.test(returnDate)) prefill.returnDate = returnDate; if (returnTime && /^([01]\d|2[0-3]):[0-5]\d$/.test(returnTime)) prefill.returnTime = returnTime; const passengers = Number(params.get("passengers")); if (Number.isInteger(passengers) && passengers >= bookingConfig.minPassengers && passengers <= bookingConfig.maxPassengers) prefill.passengers = passengers; return prefill; }
export function parsePreferredVehicle(params: URLSearchParams) { const id = params.get("vehicle"); return id && bookingVehicles.some((vehicle) => vehicle.id === id) ? id : null; }
export function saveDraft(draft: BookingDraft) { try { sessionStorage.setItem(bookingConfig.storageKey, serializeDraft(draft)); } catch { /* Booking remains usable when storage is unavailable. */ } }
export function clearStoredDraft() { try { sessionStorage.removeItem(bookingConfig.storageKey); } catch { /* No-op. */ } }
