"use client";
import { useId, useState } from "react";
import { LoaderCircle, MapPin } from "lucide-react";
import { mockLocationProvider } from "@/lib/booking/mock-location-provider";
import type { LocationSuggestion } from "@/lib/booking/location-provider";
import { cn } from "@/lib/utils";

export function LocationField({ label, value, onChange, error, placeholder }: { label: string; value: string; onChange: (value: string) => void; error?: string; placeholder: string }) {
  const id = useId(); const listId = `${id}-listbox`; const [suggestions, setSuggestions] = useState<LocationSuggestion[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [active, setActive] = useState(-1);
  const search = (query: string) => { setLoading(true); void mockLocationProvider.search(query).then((items) => { setSuggestions(items); setLoading(false); setActive(-1); }); };
  const choose = (suggestion: LocationSuggestion) => { onChange(suggestion.label); setOpen(false); setActive(-1); };
  const onKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => { if (event.key === "Escape") { setOpen(false); return; } if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActive((value) => Math.min(value + 1, suggestions.length - 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((value) => Math.max(value - 1, 0)); } if (event.key === "Enter" && open && active >= 0) { event.preventDefault(); choose(suggestions[active]); } };
  return <label className="relative block min-w-0"><span className="mb-1.5 block text-xs font-extrabold uppercase tracking-[.08em] text-muted">{label}</span><span className="relative block"><MapPin className="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-navy-800" size={18}/><input id={id} role="combobox" aria-expanded={open} aria-controls={listId} aria-autocomplete="list" aria-activedescendant={active >= 0 ? `${id}-option-${active}` : undefined} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} value={value} onChange={(event) => { onChange(event.target.value); setOpen(true); search(event.target.value); }} onFocus={() => { setOpen(true); search(value); }} onBlur={() => setTimeout(() => setOpen(false), 100)} onKeyDown={onKeyDown} className={cn("field", error && "field-error")} placeholder={placeholder} autoComplete="off" /></span>{error && <span id={`${id}-error`} className="mt-1.5 block text-xs font-bold text-danger">{error}</span>}
    {open && value.trim().length > 0 && <div id={listId} role="listbox" className="absolute inset-x-0 top-full z-30 mt-2 max-h-60 overflow-y-auto rounded-xl border border-line bg-white p-1.5 shadow-xl">{loading ? <p className="flex items-center gap-2 px-3 py-3 text-sm text-muted"><LoaderCircle className="animate-spin" size={16}/>Searching development locations…</p> : suggestions.length ? suggestions.map((suggestion, index) => <button id={`${id}-option-${index}`} role="option" aria-selected={active === index} type="button" key={suggestion.id} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(suggestion)} className={cn("flex min-h-11 w-full items-center rounded-lg px-3 text-left text-sm font-bold", active === index ? "bg-[#fff2cc] text-navy-950" : "text-ink hover:bg-warm-50")}>{suggestion.label}</button>) : <p className="px-3 py-3 text-sm text-muted">No development suggestion. You can keep your typed location.</p>}</div>}
  </label>;
}
