"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { Mail, MapPin, Phone, UserRound } from "lucide-react";
import { useForm } from "react-hook-form";
import { normalizeIndianMobile } from "@/lib/booking/phone";
import { passengerSchema, type PassengerFormValues } from "@/schemas/booking";
import type { PassengerDetails } from "@/types/booking";
import { cn } from "@/lib/utils";
function Field({ label, error, icon: Icon, children }: { label: string; error?: string; icon: typeof UserRound; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-extrabold uppercase tracking-[.08em] text-muted">{label}</span><span className="relative block"><Icon className="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-navy-800" size={18}/>{children}</span>{error && <span className="mt-1.5 block text-xs font-bold text-danger">{error}</span>}</label>; }
export function PassengerStep({ initial, onBack, onContinue }: { initial: PassengerDetails | null; onBack: () => void; onContinue: (details: PassengerDetails) => void }) { const { register, handleSubmit, formState: { errors } } = useForm<PassengerFormValues>({ resolver: zodResolver(passengerSchema), defaultValues: initial ?? { fullName: "", mobile: "", email: "", pickupNote: "" } }); const submit = (values: PassengerFormValues) => { const mobile = normalizeIndianMobile(values.mobile); if (mobile) onContinue({ ...values, mobile, email: values.email || undefined, pickupNote: values.pickupNote || undefined }); }; return <section aria-labelledby="details-step-title"><h1 id="details-step-title" tabIndex={-1} className="text-2xl font-extrabold tracking-tight text-navy-950 sm:text-3xl">Who is travelling?</h1><p className="mt-2 text-sm leading-6 text-muted">We only ask for details needed to contact you about this request.</p><form onSubmit={handleSubmit(submit)} noValidate className="mt-7 grid gap-4"><Field label="Full name" icon={UserRound} error={errors.fullName?.message}><input className={cn("field", errors.fullName && "field-error")} autoComplete="name" {...register("fullName")}/></Field><Field label="Mobile number" icon={Phone} error={errors.mobile?.message}><input className={cn("field", errors.mobile && "field-error")} type="tel" inputMode="tel" autoComplete="tel" placeholder="98765 43210" {...register("mobile")}/></Field><Field label="Email (optional)" icon={Mail} error={errors.email?.message}><input className={cn("field", errors.email && "field-error")} type="email" autoComplete="email" {...register("email")}/></Field><label><span className="mb-1.5 block text-xs font-extrabold uppercase tracking-[.08em] text-muted">Pickup note (optional)</span><span className="relative block"><MapPin className="pointer-events-none absolute left-3.5 top-4 text-navy-800" size={18}/><textarea rows={3} className={cn("field min-h-24 resize-y pt-3 pl-10", errors.pickupNote && "field-error")} placeholder="For example: Near railway station entrance" {...register("pickupNote")}/></span>{errors.pickupNote && <span className="mt-1.5 block text-xs font-bold text-danger">{errors.pickupNote.message}</span>}</label><div className="mt-3 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><button type="button" onClick={onBack} className="btn border border-line bg-white text-navy-900">Back</button><button type="submit" className="btn btn-primary">Review booking</button></div></form></section>; }
