"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { CarFront, Repeat2, Route, UsersRound } from "lucide-react";
import { Controller, useForm, useWatch } from "react-hook-form";
import { createTripSchema, type TripFormValues } from "@/schemas/booking";
import type { TripDetails } from "@/types/booking";
import { cn } from "@/lib/utils";
import { LocationField } from "./location-field";
import { DateTimePickerField } from "./date-time-picker-field";
const tabs = [{ id: "one-way", label: "One way", icon: Route }, { id: "round-trip", label: "Round trip", icon: Repeat2 }, { id: "outstation", label: "Outstation", icon: CarFront }] as const;
function NativeField({ label, error, icon: Icon, children }: { label: string; error?: string; icon: typeof UsersRound; children: React.ReactNode }) { return <label className="block min-w-0"><span className="mb-1.5 block text-xs font-extrabold uppercase tracking-[.08em] text-muted">{label}</span><span className="relative block min-w-0"><Icon className="pointer-events-none absolute left-3.5 top-1/2 z-10 -translate-y-1/2 text-navy-800" size={18}/>{children}</span>{error && <span className="mt-1.5 block text-xs font-bold text-danger">{error}</span>}</label>; }
export function TripStep({ initial, onContinue }: { initial: Partial<TripDetails> | null; onContinue: (trip: TripDetails) => void }) {
  const { register, control, handleSubmit, getValues, setValue, formState: { errors } } = useForm<TripFormValues>({ resolver: zodResolver(createTripSchema()), defaultValues: { tripType: initial?.tripType ?? "one-way", pickup: initial?.pickup ?? "", drop: initial?.drop ?? "", date: initial?.date ?? "", time: initial?.time ?? "", returnDate: initial?.returnDate ?? "", returnTime: initial?.returnTime ?? "", passengers: initial?.passengers ?? 1 } }); const tripType = useWatch({ control, name: "tripType" });
  const swap = () => { const pickup = getValues("pickup"); setValue("pickup", getValues("drop"), { shouldValidate: true }); setValue("drop", pickup, { shouldValidate: true }); };
  return <section aria-labelledby="trip-step-title"><h1 id="trip-step-title" tabIndex={-1} className="text-2xl font-extrabold tracking-tight text-navy-950 sm:text-3xl">Tell us about your trip</h1><p className="mt-2 text-sm leading-6 text-muted">Enter your journey details. You can review everything before submitting.</p><form onSubmit={handleSubmit(onContinue)} noValidate className="mt-7">
    <fieldset><legend className="sr-only">Trip type</legend><div className="grid grid-cols-3 gap-1 rounded-xl bg-[#f1f4f6] p-1">{tabs.map(({ id, label, icon: Icon }) => <label key={id} className={cn("flex min-h-12 cursor-pointer items-center justify-center gap-1 rounded-lg px-1 text-xs font-extrabold sm:text-sm", tripType === id ? "bg-navy-900 text-white" : "text-muted")}><input type="radio" value={id} className="sr-only" {...register("tripType")}/><Icon size={16}/>{label}</label>)}</div></fieldset>
    <div className="mt-5 grid gap-4"><Controller name="pickup" control={control} render={({ field }) => <LocationField label="Pickup location" placeholder="Enter pickup area or landmark" value={field.value} onChange={field.onChange} error={errors.pickup?.message}/>}/><span className="-my-3 flex h-6 items-center justify-end pr-3"><button type="button" onClick={swap} aria-label="Swap pickup and drop locations" className="grid size-10 place-items-center rounded-full border border-line bg-white text-navy-900 shadow-md"><Repeat2 className="rotate-90" size={17}/></button></span><Controller name="drop" control={control} render={({ field }) => <LocationField label="Drop location" placeholder="Enter destination" value={field.value} onChange={field.onChange} error={errors.drop?.message}/>} /></div>
    <div className="mt-4 grid gap-4 sm:grid-cols-2"><Controller name="date" control={control} render={({ field }) => <DateTimePickerField mode="date" label="Pickup date" value={field.value} onChange={field.onChange} error={errors.date?.message}/>}/><Controller name="time" control={control} render={({ field }) => <DateTimePickerField mode="time" label="Pickup time" value={field.value} onChange={field.onChange} error={errors.time?.message}/>} /></div>
    {tripType === "round-trip" && <div className="mt-4 grid gap-4 sm:grid-cols-2"><Controller name="returnDate" control={control} render={({ field }) => <DateTimePickerField mode="date" label="Return date" value={field.value ?? ""} onChange={field.onChange} error={errors.returnDate?.message}/>}/><Controller name="returnTime" control={control} render={({ field }) => <DateTimePickerField mode="time" label="Return time" value={field.value ?? ""} onChange={field.onChange} error={errors.returnTime?.message}/>} /></div>}
    <div className="mt-4"><NativeField label="Passengers" icon={UsersRound} error={errors.passengers?.message}><select className="field appearance-none" {...register("passengers", { valueAsNumber: true })}>{[1,2,3,4,5,6,7].map((number) => <option value={number} key={number}>{number} passenger{number > 1 ? "s" : ""}</option>)}</select></NativeField></div><button className="btn btn-primary mt-7 w-full sm:w-auto sm:min-w-48" type="submit">Continue to rides</button>
  </form></section>;
}
