import Link from "next/link";
import { FaWhatsapp } from "react-icons/fa6";
import { ArrowRight, CalendarCheck, CarFront, Check, CircleDot, Headphones, Luggage, MapPin, MessageCircle, Phone, Plane, Route, UsersRound } from "lucide-react";
import { BookingWidget } from "@/components/booking/booking-widget";
import { HeroMotionBackground, HeroTopVideo } from "@/components/home/hero-motion-background";
import { SwipeToCall } from "@/components/home/swipe-to-call";
import { FaqAccordion } from "@/components/faq/faq-accordion";
import { fleet, routes, services, trustItems } from "@/data/content";
import { phoneDisplay, phoneHref, whatsappHref } from "@/config/site";

function Heading({ eyebrow, title, text, centered = false }: { eyebrow: string; title: string; text?: string; centered?: boolean }) { return <div className={centered ? "mx-auto max-w-2xl text-center" : "max-w-2xl"}><p className="eyebrow">{eyebrow}</p><h2 className="section-title mt-3 text-navy-950">{title}</h2>{text && <p className="mt-4 text-base leading-7 text-muted">{text}</p>}</div>; }

export function Hero() {
  const services = ["One Way", "Round Trip", "Airport", "Outstation"];
  return <section className="relative bg-navy-950 text-white"><HeroMotionBackground/><div className="container-site relative grid min-w-0 items-center gap-8 py-9 md:gap-10 md:py-12 xl:grid-cols-[minmax(0,1.08fr)_minmax(31rem,.92fr)] xl:gap-12 xl:py-14"><div className="min-w-0 max-w-[44rem] xl:max-w-none"><HeroTopVideo/><div className="inline-flex max-w-full flex-col items-start text-[10px] font-extrabold uppercase tracking-[.08em] text-amber-500 min-[360px]:text-[11px] min-[360px]:tracking-[.1em] sm:text-xs"><span className="flex items-center gap-2"><MapPin className="shrink-0" size={15} /> Trusted taxi service <span aria-hidden="true">•</span> Villupuram</span><span className="mt-3 h-1 w-14 rounded-full bg-amber-500"/></div><h1 className="hero-word hero-word-one mt-5 max-w-[42rem] whitespace-nowrap text-[clamp(1.05rem,5.3vw,2.125rem)] font-extrabold leading-tight tracking-[-.04em] md:whitespace-normal md:text-5xl md:leading-[1.07] xl:text-[3.5rem] xl:leading-[1.04]"><span className="inline md:block">Safest. Trusted.</span><span className="ml-1 inline text-amber-500 md:ml-0 md:mt-2 md:block">Affordable Rides.</span></h1><p className="mt-4 hidden max-w-[38rem] text-sm leading-6 text-white/65 md:block md:text-base md:leading-7">Travel with confidence across Villupuram and beyond. Easy booking, dependable service and affordable fares for one-way, round-trip, airport and outstation travel.</p><SwipeToCall href={phoneHref} phone={phoneDisplay}/><div className="mt-7 grid min-w-0 gap-3 min-[430px]:grid-cols-2 sm:flex sm:flex-wrap"><Link href="/book" className="btn btn-primary w-full px-6 sm:w-auto"><CalendarCheck size={18}/>Book a taxi</Link><a href={phoneHref} aria-label={`Call ${phoneDisplay}`} className="btn btn-secondary w-full px-6 sm:w-auto"><Phone size={18}/>Call now</a></div><div aria-label="Available taxi services" className="mx-auto mt-7 flex max-w-full flex-wrap items-center justify-center gap-x-4 gap-y-3 text-xs font-bold text-white md:text-sm">{services.map((service) => <span key={service} className="flex min-w-0 items-center gap-1.5"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-white text-navy-950"><Check size={13} strokeWidth={3}/></span>{service}</span>)}</div></div><div className="w-full min-w-0 max-w-[51.25rem] xl:max-w-none"><BookingWidget /></div></div></section>;
}

export function TrustStrip() { return <section aria-label="Service standards" className="border-b border-line bg-white"><div className="container-site grid grid-cols-2 gap-x-4 gap-y-6 py-7 md:grid-cols-4 md:gap-x-0">{trustItems.map(({ title, note, icon: Icon }, index) => <div key={title} className={`flex min-w-0 flex-col gap-2 md:flex-row md:items-start md:gap-3 md:px-5 ${index > 0 ? "md:border-l md:border-line" : ""}`}><span className="grid size-10 shrink-0 place-items-center rounded-xl border border-line bg-warm-50 text-navy-900"><Icon size={20} /></span><div className="min-w-0"><h2 className="text-xs font-extrabold text-navy-950 min-[430px]:text-sm">{title}</h2><p className="mt-1 text-[10px] leading-4 text-muted min-[430px]:text-xs">{note}</p></div></div>)}</div></section>; }

export function RoutesSection() { return <section id="routes" className="section-space"><div className="container-site"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><Heading eyebrow="Popular routes" title="Popular rides from Villupuram" text="Start with a common destination or enter any route above." /><Link href="/book" className="hidden shrink-0 items-center gap-2 text-sm font-extrabold text-navy-900 sm:flex">Plan a custom route <ArrowRight size={17} /></Link></div><div className="mt-9 grid min-w-0 gap-4 sm:grid-cols-2 lg:grid-cols-3">{routes.map((destination, index) => <article key={destination} className="group min-w-0 rounded-2xl border border-line bg-white p-4 transition-all hover:-translate-y-1 hover:border-amber-500 hover:shadow-[var(--shadow-card)] min-[430px]:p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-navy-950 text-amber-500"><Route size={19} /></span><span className="text-[10px] font-extrabold uppercase tracking-[.12em] text-muted">Route {String(index + 1).padStart(2,"0")}</span></div><div className="mt-7 grid min-w-0 grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-center gap-2 sm:gap-3"><div className="min-w-0"><span className="text-[10px] font-bold uppercase tracking-wider text-muted">From</span><h3 className="mt-1 break-words text-sm font-extrabold text-navy-950 min-[360px]:text-base">Villupuram</h3></div><div className="flex items-center"><CircleDot className="shrink-0 text-amber-500" size={12} /><span className="w-4 border-t border-dashed border-line min-[430px]:w-6 sm:w-10" /><MapPin className="shrink-0 text-navy-800" size={15} /></div><div className="min-w-0"><span className="text-[10px] font-bold uppercase tracking-wider text-muted">To</span><p className="mt-1 break-words text-sm font-extrabold text-navy-950 min-[360px]:text-base">{destination}</p></div></div><Link href={`/book?pickup=Villupuram&drop=${encodeURIComponent(destination)}`} className="mt-6 flex min-h-11 items-center justify-between rounded-xl bg-[#f5f7f8] px-4 text-sm font-extrabold text-navy-900 transition-colors group-hover:bg-amber-500">Check fare <ArrowRight className="shrink-0" size={17} /></Link></article>)}</div></div></section>; }

function CarVisual({ name }: { name: string }) { return <div className="relative h-36 overflow-hidden rounded-2xl bg-[#edf1f4]"><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-[#d7dfe5] to-transparent"/><CarFront className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-navy-800" size={94} strokeWidth={1.15}/><span className="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider text-muted">Visual placeholder</span><span className="sr-only">Placeholder visual for {name}</span></div>; }
export function FleetSection() { return <section id="fleet" className="section-space bg-white"><div className="container-site"><Heading eyebrow="Our fleet" title="Choose the ride that fits your trip" text="Practical options for solo travel, families and larger groups." centered /><div className="mt-9 grid min-w-0 gap-5 md:grid-cols-2 xl:grid-cols-4">{fleet.map((car) => <article key={car.name} className="min-w-0 rounded-[1.35rem] border border-line bg-warm-50 p-3 transition-transform hover:-translate-y-1"><CarVisual name={car.name}/><div className="min-w-0 px-2 pb-2 pt-5"><h3 className="break-words text-xl font-extrabold text-navy-950">{car.name}</h3><p className="mt-1 text-xs text-muted">{car.model}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-muted"><span className="flex items-center gap-1.5 rounded-lg bg-white px-2.5 py-2"><UsersRound size={15}/>{car.passengers}</span><span className="flex items-center gap-1.5 rounded-lg bg-white px-2.5 py-2"><Luggage size={15}/>{car.luggage}</span><span className="flex items-center gap-1.5 rounded-lg bg-white px-2.5 py-2"><Check size={15}/>AC</span></div><div className="mt-5 flex min-w-0 items-center justify-between gap-3 border-t border-line pt-4"><div className="min-w-0"><p className="text-[10px] font-bold uppercase text-muted">Pricing</p><p className="break-words text-sm font-extrabold text-navy-950">Rate on request</p></div><Link href={`/book?vehicle=${car.tone}`} className="grid size-11 shrink-0 place-items-center rounded-xl bg-navy-900 text-white" aria-label={`Select ${car.name}`}><ArrowRight size={18}/></Link></div></div></article>)}</div></div></section>; }

export function ServicesSection() { return <section id="services" className="section-space"><div className="container-site"><Heading eyebrow="Ways to travel" title="A taxi for every kind of journey" text="Simple travel options designed around where you need to go." /><div className="mt-9 grid min-w-0 gap-x-6 gap-y-4 md:grid-cols-2 xl:grid-cols-3">{services.map(({ slug, name, text, icon: Icon }) => <article key={name} className="group flex min-w-0 gap-4 rounded-2xl border border-transparent p-3 transition-colors hover:border-line hover:bg-white min-[430px]:p-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-[#fff2cc] text-amber-600 transition-colors group-hover:bg-amber-500 group-hover:text-navy-950"><Icon size={22}/></span><div className="min-w-0"><h3><Link href={`/services/${slug}`} className="font-extrabold text-navy-950 underline decoration-transparent underline-offset-4 group-hover:decoration-amber-500">{name}</Link></h3><p className="mt-1.5 text-sm leading-6 text-muted">{text}</p></div></article>)}</div><Link href="/services" className="btn border border-line bg-white text-navy-900 mt-7">View all services</Link></div></section>; }

export function AirportSection() { return <section id="airport" className="pb-6"><div className="container-site"><div className="route-grid relative min-w-0 overflow-hidden rounded-[1.5rem] bg-navy-950 px-5 py-10 text-white min-[430px]:px-7 sm:px-10 lg:px-14 lg:py-14"><div className="pointer-events-none absolute right-5 top-1/2 hidden -translate-y-1/2 text-white/[.035] xl:block"><Plane size={280} strokeWidth={1}/></div><div className="relative min-w-0 max-w-2xl"><span className="grid size-12 place-items-center rounded-xl bg-amber-500 text-navy-950"><Plane size={23}/></span><p className="eyebrow mt-6 text-amber-500">Airport transfers</p><h2 className="section-title mt-3">A smoother start to your airport journey.</h2><p className="mt-4 max-w-xl leading-7 text-white/65">Plan pickups and drops between Villupuram, Chennai Airport and Pondicherry Airport. Route availability and charges are confirmed with your request.</p><div className="mt-7 flex min-w-0 flex-wrap gap-2 text-xs font-bold text-white/75">{["Villupuram → Chennai Airport","Chennai Airport → Villupuram","Villupuram → Pondicherry Airport"].map((r) => <span key={r} className="max-w-full rounded-full border border-white/15 bg-white/5 px-3 py-2">{r}</span>)}</div><Link href="/book?tripType=airport&pickup=Villupuram&drop=Chennai%20Airport" className="btn btn-primary mt-8 w-full min-[430px]:w-auto"><CalendarCheck size={18}/>Book airport taxi</Link></div></div></div></section>; }

export function ProcessSection() { const steps = ["Enter your trip","Choose your car","Check your fare","Confirm your ride"]; return <section className="section-space bg-white"><div className="container-site"><Heading eyebrow="How it works" title="Your ride, planned in four simple steps" centered/><ol className="relative mt-10 grid gap-6 md:grid-cols-2 md:gap-8 xl:grid-cols-4 xl:gap-4 before:absolute before:left-[12.5%] before:right-[12.5%] before:top-7 before:hidden before:border-t before:border-dashed before:border-line xl:before:block">{steps.map((step,index) => <li key={step} className="relative flex min-w-0 items-center gap-4 bg-white xl:flex-col xl:text-center"><span className="relative z-10 grid size-14 shrink-0 place-items-center rounded-full border-4 border-white bg-navy-950 text-sm font-extrabold text-amber-500 shadow-lg">{String(index+1).padStart(2,"0")}</span><h3 className="min-w-0 font-extrabold text-navy-950">{step}</h3></li>)}</ol></div></section>; }

export function ReviewsSection() { return <section id="about" className="section-space"><div className="container-site"><div className="grid min-w-0 gap-7 rounded-[1.5rem] border border-line bg-white p-5 sm:p-7 lg:grid-cols-[.8fr_1.2fr] lg:items-center lg:p-10"><div className="min-w-0"><p className="eyebrow">Customer stories</p><h2 className="section-title mt-3">Trust should come from real experiences.</h2></div><div className="min-w-0 rounded-2xl border border-dashed border-line bg-warm-50 p-5 text-center sm:p-7"><MessageCircle className="mx-auto text-amber-600" size={28}/><h3 className="mt-4 font-extrabold text-navy-950">Customer reviews will appear here</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted">This space is intentionally reserved for verified customer or Google reviews supplied by the client.</p></div></div></div></section>; }

export function FaqSection() { return <section className="section-space bg-white"><div className="container-site grid min-w-0 gap-8 xl:grid-cols-[.72fr_1.28fr] xl:gap-16"><div className="min-w-0"><Heading eyebrow="Helpful answers" title="Before you book" text="The service policies below are provisional until approved by the operator."/><div className="mt-7 flex min-w-0 items-center gap-3 rounded-xl bg-warm-50 p-4 text-sm font-bold text-navy-900"><Headphones size={20} className="shrink-0 text-amber-600"/><span className="min-w-0">Still unsure? Contact booking support.</span></div></div><FaqAccordion/></div></section>; }

export function FinalCta() { return <section className="bg-amber-500"><div className="container-site flex min-w-0 flex-col justify-between gap-7 py-10 lg:flex-row lg:items-center lg:py-12"><div className="min-w-0"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-navy-800">Ready when you are</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-navy-950 sm:text-4xl">Need a ride from Villupuram?</h2><p className="mt-3 text-sm font-semibold text-navy-800 sm:text-base">Tell us where you’re going and we’ll help you plan your trip.</p></div><div className="grid w-full min-w-0 gap-3 sm:w-auto sm:grid-cols-2 lg:flex lg:flex-wrap"> <Link href="/book" className="btn btn-navy w-full"><CalendarCheck size={18}/>Book taxi</Link><a href={phoneHref} className="btn w-full border border-navy-900/20 bg-white/65 text-navy-950"><Phone size={18}/>Call now</a>{whatsappHref && <a href={whatsappHref} className="btn w-full border border-navy-900/20 bg-transparent text-navy-950"><FaWhatsapp size={18}/>WhatsApp</a>}</div></div></section>; }
