import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Check, MapPin, Route as RouteIcon } from "lucide-react";
import { PageHero } from "@/components/content/page-hero";
import { RouteCard } from "@/components/content/route-card";
import { StaticFaq, type FaqItem } from "@/components/content/static-faq";
import { FinalBookingCta } from "@/components/content/final-booking-cta";
import { JsonLd } from "@/components/seo/json-ld";
import { bookingVehicles } from "@/data/booking-vehicles";
import { getTaxiRoute, publishedTaxiRoutes } from "@/data/taxi-routes";
import { createMetadata } from "@/lib/metadata";
import { createBreadcrumbSchema, createFaqSchema, createServiceSchema } from "@/lib/structured-data";
export function generateStaticParams() { return publishedTaxiRoutes.map((route) => ({ slug: route.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const route = getTaxiRoute(slug); return route ? createMetadata({ title: route.seo.title, description: route.seo.description, path: route.seo.canonicalPath }) : {}; }
export default async function RoutePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const route = getTaxiRoute(slug); if (!route) notFound(); const bookHref = `/book?pickup=${encodeURIComponent(route.origin)}&drop=${encodeURIComponent(route.destination)}${route.airportRoute ? "&tripType=airport" : ""}`; const crumbs = [{ label: "Home", href: "/" }, { label: "Routes", href: "/routes" }, { label: route.title }]; const faqs: FaqItem[] = [{ question: `Can I request a one-way taxi from ${route.origin} to ${route.destination}?`, answer: "Yes, choose One Way in the booking flow. Route coverage and current fare are confirmed before the request is accepted." }, { question: "Can I request a round trip?", answer: "Where applicable, choose Round Trip and provide both return date and time. The operator will review the complete requirement." }, { question: "How is the fare calculated?", answer: "Fare depends on the confirmed route, trip type, vehicle and applicable operating charges. Final client pricing policies are still being configured." }, { question: "Can I choose the vehicle category?", answer: "You can request Sedan, MPV, Innova or Innova Crysta. The exact model and availability are confirmed by the operator." }]; const related = route.relatedRoutes.map(getTaxiRoute).filter((item): item is NonNullable<typeof item> => Boolean(item)); return <main id="main-content"><JsonLd data={createBreadcrumbSchema(crumbs)}/><JsonLd data={createServiceSchema({ name: route.title, description: route.shortDescription, path: route.seo.canonicalPath, areaServed: [route.origin, route.destination] })}/><JsonLd data={createFaqSchema(faqs)}/><PageHero breadcrumbs={crumbs} eyebrow={route.serviceTypes.map((type) => type.replace("-", " ")).join(" • ")} title={route.title} description={route.shortDescription} bookingHref={bookHref} bookingLabel="Book this route"/>
  <section className="border-b border-line bg-white"><div className="container-site grid gap-5 py-7 sm:grid-cols-2 lg:grid-cols-4">{[["From",route.origin],["To",route.destination],["Trip types",route.serviceTypes.slice(0,2).map((type) => type.replace("-"," ")).join(" / ")],["Fare","Contact for current fare"]].map(([label,value]) => <div key={label} className="min-w-0"><p className="text-[10px] font-extrabold uppercase tracking-wider text-muted">{label}</p><p className="mt-1 break-words font-extrabold capitalize text-navy-950">{value}</p></div>)}</div></section>
  <div className="container-site section-space"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr]"><section><p className="eyebrow">Route overview</p><h2 className="section-title mt-3 text-navy-950">Plan the journey around your needs</h2><p className="mt-5 leading-7 text-muted">Planning travel from {route.origin} to {route.destination}? Enter your timing and passenger count, choose a suitable vehicle and send the details for confirmation. One-way and return options are shown only as request types—not guaranteed operating promises.</p><ul className="mt-6 grid gap-3">{route.highlights.map((highlight) => <li key={highlight} className="flex gap-3 text-sm leading-6 text-ink"><Check className="mt-0.5 shrink-0 text-success" size={18}/>{highlight}</li>)}</ul></section><section className="rounded-2xl bg-navy-950 p-6 text-white"><RouteIcon className="text-amber-500" size={28}/><h2 className="mt-4 text-2xl font-extrabold">Get the current fare</h2><p className="mt-3 text-sm leading-6 text-white/65">Fare depends on vehicle and trip requirements. Toll, parking, driver allowance and permit treatment will follow the client’s confirmed policy.</p><Link href={bookHref} className="btn btn-primary mt-6 w-full">Check fare</Link><Link href="/tariff" className="mt-3 flex min-h-11 items-center justify-center text-sm font-extrabold text-white underline underline-offset-4">View fare information</Link></section></div>
  <section className="mt-16"><p className="eyebrow">Vehicle options</p><h2 className="section-title mt-3 text-navy-950">Choose around passengers and luggage</h2><p className="mt-3 text-sm text-muted">Vehicle options may vary by availability.</p><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{bookingVehicles.map((vehicle) => <article key={vehicle.id} className="rounded-2xl border border-line bg-white p-5"><h3 className="font-extrabold text-navy-950">{vehicle.name}</h3><p className="mt-1 text-xs text-muted">{vehicle.exampleModels}</p><p className="mt-4 text-sm text-muted">Up to {vehicle.passengers} passengers · {vehicle.luggage} bags · AC</p><Link href={`${bookHref}&vehicle=${vehicle.id}`} className="btn btn-navy mt-5 w-full text-sm">Choose this ride</Link></article>)}</div></section>
  <section className="mt-16 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-line bg-white p-6"><h2 className="text-xl font-extrabold text-navy-950">Pickup information</h2>{route.pickupGuidance.map((item) => <p key={item} className="mt-3 flex gap-2 text-sm leading-6 text-muted"><MapPin className="mt-1 shrink-0 text-amber-600" size={16}/>{item}</p>)}</div><div className="rounded-2xl border border-line bg-white p-6"><h2 className="text-xl font-extrabold text-navy-950">Destination information</h2>{route.destinationGuidance.map((item) => <p key={item} className="mt-3 flex gap-2 text-sm leading-6 text-muted"><MapPin className="mt-1 shrink-0 text-amber-600" size={16}/>{item}</p>)}</div></section>
  <section className="mt-16"><p className="eyebrow">Questions</p><h2 className="section-title mt-3 text-navy-950">Route FAQ</h2><div className="mt-7"><StaticFaq items={faqs}/></div></section>{related.length > 0 && <section className="mt-16"><p className="eyebrow">Keep exploring</p><h2 className="section-title mt-3 text-navy-950">Related routes</h2><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{related.map((item) => <RouteCard key={item.slug} route={item}/>)}</div></section>}</div><FinalBookingCta title={`Ready to request your ${route.origin} to ${route.destination} taxi?`} bookingHref={bookHref}/></main>; }
